### ISSUE TITLE
IRC contact wrong?

### ISSUE THREAD

**Issue by darkf** [deathstar/QServCollect#3]
Joined, ain't nobody in there, is it active?

**Comment by deathstar** [comment]
The channel is not very active, it was at one point but I stopped joining and everyone left.

**Comment by deathstar** [comment]
Regardless - glad to see your still around and that you dropped a line. If you want to change anything, feel free to as I have been working on and off for a while now. Hope all is well with you.
- George

**Comment by darkf** [comment]
Hehe, glad to see you recognize me! I was going to surprise you, but yeah, nobody was there. Is there somewhere else we could reach you?

**Comment by deathstar** [comment]
I always check my email: gscottmalibu@gmail.com and I have a Skype @dordiscott but I'll join and leave IRC every couple days or so lol. Really liking Tesseract and looking forward to a new Cube (if its happening). Would be fun to reunite with some buddies too I gotta come on IRC.
