### ISSUE TITLE
Windows Support! :D

### ISSUE THREAD

**Issue by DragonSlayer87** [deathstar/QServCollect#8]
Hi Deathstar,
You probably remember me as fraggod. I just wanted to ask u if you could make a windows support in the latest qserver version just like you did with your previous ones. They had exe files and everything worked fine, except that it was made for justice edition. So i beg you, can u do the same with this version. I know u have said to download virutal and stuff, but really i cant figure it out and it has been months. So please to stop u beeing disturbed and there are many who use ure mod even today, could you please make the qservcollect compatible for windows. Do this for the community and for a old homie :) If you work with ure tech team they can probably help you with windows stuff. Ive sent u a gmail with more details. 
You have done it once https://github.com/deathstar/QServ/downloads so it wont be a problem for you. 

Thx, I appericiate it and i love your mod its WONDERFUCKINGFUL 
-Your Homie, FragGoD

**Comment by deathstar** [comment]
Glad you like it, thank you for helping port it. :)
